### ISSUE TITLE
Hello,打扰您一下！

### ISSUE THREAD

**Issue by PandaAD** [Famine-Life/exercise-wonder#2]
您好，我这个学期正在自学spring，边改边学，能麻烦您发一下这个项目的数据库嘛？自己调的总是有问题，不好意思哇。

**Comment by Famine-Life** [comment]
好的，大概13点我传上去。



---原始邮件---
发件人: "PandaAD"<notifications@github.com&gt;
发送时间: 2020年4月14日(周二) 上午10:08
收件人: "Famine-Life/exercise-wonder"<exercise-wonder@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Famine-Life/exercise-wonder] Hello,打扰您一下！ (#2)




 
您好，我这个学期正在自学spring，边改边学，能麻烦您发一下这个项目的数据库嘛？自己调的总是有问题，不好意思哇。

**Comment by PandaAD** [comment]
非常感谢！

**Comment by Famine-Life** [comment]
已传。

**Comment by PandaAD** [comment]
看到了，谢谢！
